### ISSUE TITLE
Continuing converstions started from org-ai-on-region

### ISSUE THREAD

**Issue by mrspeaker** [rksm/org-ai#29]
I'm really loving the new non-org functions (org-ai-on-region is fantastically helpful), but there are many times when I find myself wanting to continue or refine the conversation from the output. Currently that means copy/pasting and retyping prompts in an org buffer.

Is there any way to have the output of the non-org functions be the full session in a new org-mode buffer (or something like that)?

**Comment by lambdaofgod** [comment]
I imagine an use case where you have a bunch of org mode files open for making notes and you'd like to store stuff that LM generated out of code. A quick workaround in this context would be to just have a function that will append contents of the current buffer to an org mode file that you opened already.

I've written (using GPT of course) the following code to do just this

```
(defvar my/handled-file-paths '()
  "List of previously handled file paths.")

(defun my/org-buffers ()
  "Return a list of file paths for currently-open Org-mode buffers."
  (delq nil
        (mapcar (lambda (buf)
                  (with-current-buffer buf
                    (when (equal major-mode 'org-mode)
                      (buffer-file-name))))
                (buffer-list))))

(defun my/append-to-file ()
  "Append the contents of the current buffer to a user-selected file, and store the selected file path for future use.
Allow choosing the file path from currently opened Org-mode buffers."
  (interactive)
  (let ((default-directory (if my/handled-file-paths (car handled-file-paths) default-directory)))
    (let* ((org-buffers (my-org-buffers))
           (buffer-names (mapcar 'file-name-nondirectory org-buffers))
           (selected-buffer-name (completing-read "Append to file (choose from Org buffers or type in a new one): " buffer-names nil nil nil nil (car buffer-names)))
           (selected-buffer-path (car (or (cl-member selected-buffer-name buffer-names :test #'string=) (list selected-buffer-name)))))
      (let ((file-path (expand-file-name selected-buffer-path)))
        ;; Add the selected file path to the list if it's not already there.
        (unless (member file-path my/handled-file-paths)
          (setq my/handled-file-paths (cons file-path handled-file-paths)))

        ;; Append the current buffer contents to the selected file.
        (write-region (buffer-string) nil file-path 'append)
        (message "Appended contents to: %s" file-path)))))
```

# Questions

- Do we store a default file for notes or just assume the users will use their opened org buffers?
- The version I proposed just concatenates the outputs to the file, do we wrap this in an org-ai block with appropriate markup?
- (more advanced) what would be the best way to integrate this so that we do not only get the outputs, but also the prompt?

**Comment by rksm** [comment]
Yeah I think both should be possible, continuing a conversation and storing it.

For continuing the conversation, the easiest option would probably be to simply activate `org-mode` in the result buffer and then inserting both the prompt as well as the answer into an org-ai block. Continuing from there would be natural. The only downside would be that it would be a bit more noise than seeing just the output, but I think that is in the interest of versatility.

And I also like the idea of adding a local minor mode to that buffer to save the content or append the content to an existing file.

I'll first look into the former option.

**Comment by rksm** [comment]
> And I also like the idea of adding a local minor mode to that buffer to save the content or append the content to an existing file.

Actually for this, we could simply store the answers if there is some customizable variable set, like `org-ai-store-conversations`. We already store the prompts when generating images, we could deal with it the same way. This way you get a record of your conversations (if you enable that option) but don't need to deal with additional commands.

**Comment by lambdaofgod** [comment]
Yeah this makes sense and it ties nicely with the #27. I think it makes sense to store conversations because if we do this well we can put conversations in vector store and POOF, we have kinda memory mechanism.

I propose to do the following:
- log everything to log files by default
- optionally disable storage
- store conversations in org mode using #+begin_ai... blocks
- add metadata to the blocks (I imagine it would be important to store what model was used, latency et c)
- store log files in some default directory like "~/.org-ai/logs", split them by date

It's likely I'll handle this by the end of next week, the only thing is that we need to come up with some kind of format for metadata (so that we'll be able to easily put this stuff in a database like mongo et c)

**Comment by rksm** [comment]
https://github.com/rksm/org-ai/commit/248c332bb2651d0daa92b2a479a4c0da343a9458 modifies the behavior of  `org-ai-on-region`.

It now outputs both prompt and answer into an `org-mode` buffer together with a link (if available) to the location from where the command was run and a timestamp.

It is optionally possible to customize the variable `org-ai-on-region-file` to specify a file to store the conversations in.

E.g.
```
(setq org-ai-on-region-file (expand-file-name "org-ai-on-region.org" org-directory))
```.

New prompts will be appended to this file.

**Comment by rksm** [comment]
Feel free to reopen if you think something should change or something doesn't work.
